[build]
	publish = "dist"
	command = "npm run build"

[[redirects]]
	from = "/*"
	to = "index.html"
	status = 200

[[headers]]
	for = "/*"
	[headers.values]
		# X-Frame-Options = "SAMEORIGIN"
		X-XSS-Protection = "1"
		X-Content-Type-Options = "nosniff"